### ISSUE TITLE
Create a docker toy 

### ISSUE THREAD

**Issue by heatheranndye** [heatheranndye/ImageToStyle#10]
ML code takes forever to load.

**Comment by heatheranndye** [comment]
@Zaubeerer   stripped out the ml because it took forever to load. 

I can get both the streamlit and the fastapi to run in their containers, but I can't get them to communicate. I am not sure if it is an error in the docker files or if it is a requests error in  stream_ml.   The host/server addresses are different in docker destop and vscode. 

This branch is not designed to be merged. Once I figure out what the issue is, I'm just going to delete it.

**Comment by Zaubeerer** [comment]
OK, sounds like a good topic to tackle in a sync session :)

We could meet tomorrow.

**Comment by heatheranndye** [comment]
I've got the job interview (three 45 minute sessions on Friday).  Meeting next week would work best.
