### ISSUE TITLE
Question about Docker and Volumes.

### ISSUE THREAD

**Issue by heatheranndye** [heatheranndye/ImageToStyle#5]
I think I need to mount a volume to store the images for the image program.  I'm using the Docker tutorial and a sample from streamlit.  Both samples use git clone, so the file isn't in my github.   The program is with the data folder.  I can create a volume but I'm not sure how the data "goes into" the volume?  The Docker tutorial example starts with an empty volume and then they move quickly onto to bind mounts.  

```
(# app/Dockerfile

FROM python:3.9-slim

EXPOSE 8501

WORKDIR /app

RUN apt-get update && apt-get install -y \

    build-essential \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/streamlit/streamlit-example.git .

RUN pip3 install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]) 
```

**Comment by heatheranndye** [comment]
@Zaubeerer

**Comment by Zaubeerer** [comment]
Yeah, the code you shared does not yet do anything related to the mounting 🤔 

Actually, I would maybe first challenge a bit whether you really need to mount a volume, but I am not sure myself.

I could imagine, that the image can also be saved as bite object and then given to whatever function  requires the image input?
