### ISSUE TITLE
Flatten File Structure and Redo Dockerfiles

### ISSUE THREAD

**Issue by heatheranndye** [heatheranndye/ImageToStyle#6]
Found this sample: https://github.com/davidefiocco/streamlit-fastapi-model-serving 
Checked the container and the images are in container.   

Tasks:

- [ ] Flatten File structure
- [ ] Make docker folders?  
- [ ]

**Comment by Zaubeerer** [comment]
Hey Heather, Can you elaborate, what you mean by this?

Do you need any feedback from me?

**Comment by heatheranndye** [comment]
Found this sample code:
https://github.com/davidefiocco/streamlit-fastapi-model-serving 

The image files are in the docker container.  (I checked the file structure but the paths are different from when I run it from the terminal.)
I think that I need to fix a path reference - change the way I coded it, since the path changes in the docker container.  

I don't really understand the volume part, but I haven't actually thought about it in a few days.
